improved commands

diff --git a/.ddev/commands/web/dkan-frontend-install b/.ddev/commands/web/dkan-frontend-install
--- a/.ddev/commands/web/dkan-frontend-install
+++ b/.ddev/commands/web/dkan-frontend-install
@@ -7,6 +7,7 @@ FRONTEND_TMP='src/tmp'
 FRONTEND_DIR='src/frontend'
 FRONTEND_DOCROOT_DIR='docroot/frontend'
 FRONTEND_VCS_URL='https://github.com/GetDKAN/data-catalog-app/'
+# TODO: no-node-sass is the known-good branch, so we should move that forward to be a release.
 #FRONTEND_VCS_REF='cypress-update-8.7.0'
 #FRONTEND_VCS_REF='1.0.4'
 FRONTEND_VCS_REF='no-node-sass'
@@ -19,10 +20,10 @@ if [[ -L $FRONTEND_DOCROOT_DIR ]]; then
   exit 1
 fi
 
-if [ -d $FRONTEND_DIR ]; then
-  echo "ERROR: Frontend $FRONTEND_DIR already exists."
-  exit 1
-fi
+#if [ -d $FRONTEND_DIR ]; then
+ # echo "ERROR: Frontend $FRONTEND_DIR already exists."
+  #exit 1
+#fi
 
 composer require getdkan/$FRONTEND_THEME
 drush theme:enable $FRONTEND_THEME
@@ -34,10 +35,10 @@ drush config-set system.theme default $FRONTEND_THEME -y
 
 mkdir -p $FRONTEND_TMP
 wget -O $FRONTEND_TMP/data-catalog-app-$FRONTEND_VCS_REF.zip "$FRONTEND_VCS_URL"archive/$FRONTEND_VCS_REF.zip
-unzip $FRONTEND_TMP/data-catalog-app-$FRONTEND_VCS_REF.zip -d src/
-mv src/data-catalog-app-$FRONTEND_VCS_REF src/frontend
+unzip $FRONTEND_TMP/data-catalog-app-$FRONTEND_VCS_REF.zip -d docroot/
+mv docroot/data-catalog-app-$FRONTEND_VCS_REF docroot/frontend
 
-ln -s $PWD/$FRONTEND_DIR $FRONTEND_DOCROOT_DIR
+#ln -s $PWD/$FRONTEND_DIR $FRONTEND_DOCROOT_DIR
 
 cd $FRONTEND_DOCROOT_DIR || exit
 npm install
